/**
 * Generate `apps/desktop/deploy-root/package.json` — the dependency-only
 * deploy root whose closure IS the desktop backend payload.
 *
 * The root lists every workspace package reachable from `@deepseek-ai/dsh`'s
 * dependencies through each package's dependencies, peerDependencies, and
 * optionalDependencies. Listing peers explicitly is required: pnpm deploy
 * with `--prod` drops workspace peers that are also devDependencies of their
 * owner, and the runtime boots fail loud on the first missing one
 * (`verify-runtime-closure` enforces the same invariant on the committed
 * manifest). Non-workspace npm dependencies are deliberately omitted — pnpm
 * deploys them transitively.
 *
 * Regenerate after a dependency change and re-run
 * `pnpm run verify-runtime-closure -- --manifest apps/desktop/deploy-root/package.json`.
 * @module @deepseek-ai/dsh-desktop/generate-deploy-root
 */

import { globSync, readFileSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

interface PackageManifest {
  name?: string
  dependencies?: Record<string, string>
  peerDependencies?: Record<string, string>
  optionalDependencies?: Record<string, string>
}

const root = resolve(fileURLToPath(new URL('../../..', import.meta.url)))
const DEPLOY_ROOT_DIR = join(root, 'apps/desktop/deploy-root')
const APP_PACKAGE = '@deepseek-ai/dsh'
const VERSION = '0.1.0-rc.5'
/** Load every workspace member manifest: packages, vendor, and apps. */
function loadWorkspace(): Map<string, PackageManifest> {
  const paths = globSync(['packages/*/*/package.json', 'vendor/*/package.json', 'apps/*/package.json'], { cwd: root })
  const workspace = new Map<string, PackageManifest>()
  for (const relative of paths) {
    const manifest = JSON.parse(readFileSync(join(root, relative), 'utf8')) as PackageManifest
    if (manifest.name !== undefined) workspace.set(manifest.name, manifest)
  }
  return workspace
}

/** BFS the workspace closure from one package's dependencies, collecting every reachable workspace package. */
function closureFrom(app: PackageManifest, workspace: Map<string, PackageManifest>): string[] {
  const deps: string[] = []
  const queue = [...Object.keys(app.dependencies ?? {})]
  while (queue.length > 0) {
    const name = queue.shift() as string
    if (deps.includes(name)) continue
    const manifest = workspace.get(name)
    if (manifest === undefined) continue
    deps.push(name)
    for (const dependency of Object.keys({
      ...manifest.dependencies,
      ...manifest.peerDependencies,
      ...manifest.optionalDependencies,
    })) {
      if (workspace.has(dependency) && !deps.includes(dependency)) queue.push(dependency)
    }
  }
  return deps.sort()
}

const workspace = loadWorkspace()
const app = workspace.get(APP_PACKAGE)
if (app === undefined) throw new Error(`generate-deploy-root: ${APP_PACKAGE} is not a workspace member`)
const dependencies: Record<string, string> = {}
// The CLI itself is deployed as part of the closure: its lib/ and config/
// ship inside node_modules/@deepseek-ai/dsh, so the payload needs no manual
// copy and the profile module fallback's installation anchor resolves
// naturally. (verify-runtime-closure ignores apps/* packages, so the launcher
// does not participate in the peer check.)
dependencies[APP_PACKAGE] = 'workspace:^'
for (const name of closureFrom(app, workspace)) dependencies[name] = 'workspace:^'

const manifest = {
  name: 'dsh-desktop-web-runtime-pkg',
  description: 'Dependency-only deploy root defining the desktop backend closure; pnpm deploy materializes this manifest and node_modules. Generated by scripts/generate-deploy-root.ts; regenerate after dependency changes and keep verify-runtime-closure green.',
  version: VERSION,
  private: true,
  type: 'module',
  dependencies,
}

await writeFile(join(DEPLOY_ROOT_DIR, 'package.json'), `${JSON.stringify(manifest, null, 2)}\n`)
console.log(`generate-deploy-root: wrote ${Object.keys(dependencies).length} workspace dependencies to ${join(DEPLOY_ROOT_DIR, 'package.json')}`)
